DATA:
  data_path: ./
  STREAM:
      topic: movielog6
      stream_name: test
      # How many message streamed each udpate
      num_new_messages_per_update: 2
      # Max size of message to keep (False to keep everything) [don't apply to mongo atlas]
      max_ent: 2
      # Add movie/user details
      add_external_features: True
      # file name suffix of ouput
      processed_suffix: _processed      
      
MONGO_ATLAS:
    # update streamed result to mongo atlas
    upload: True
    # connection credentials
    CONNECTION:
        host: cluster0.xuddjop.mongodb.net
        insert_to_collection: combined-rateonly
        db: movielog
        username: mlproduction
        password: pulp_prediction